name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun lint
      - name: Types
        run: bun types
      - name: Test
        run: bun test
