steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mars-rover-439913/mars-rover:$COMMIT_SHA', '.']
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mars-rover-439913/mars-rover:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mars-rover'
      - '--image'
      - 'gcr.io/mars-rover-439913/mars-rover:$COMMIT_SHA'
      - '--region'
      - 'europe-west2'
      - '--platform'
      - 'managed'

images:
  - 'gcr.io/mars-rover-439913/mars-rover:$COMMIT_SHA'
